name: football_analysis
channels:
  - default
  - conda-forge
dependencies:
  - pip
  - python
  - jupyter
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - black
  - pip:
    - supervision
    - ultralytics=8.0.196
    - opencv
